### ISSUE TITLE
Aid move is out-of-date

### ISSUE THREAD

**Issue by silverhammermba** [acodispo/Dungeon-World-HTML-SRD#7]
The text of the aid move in the github repo was recently updated recently (to reflect the final print version of the rules): https://github.com/Sagelt/Dungeon-World/blob/master/text/Moves.xml#L39

The restriction on only aiding someone you have a bond with was removed.

**Comment by acodispo** [comment]
Thanks @silverhammermba ! If you get to it before I do, feel free to open a pull request. Otherwise I'll fix it soon-ish.

**Comment by acodispo** [comment]
Fixed in 74cc71628658b8b3
